// База данных подсказок с полной документацией
export const COMPLETION_ITEMS = {
    'name': { detail: 'Название юнита', docs: 'Уникальное имя бнита (строка)' },
    'class': { detail: 'класс', docs: 'Главный класс мода' },
    'price': { detail: 'Стоимость', docs: 'Цена в ресурсах (число)' },
    'mass': { detail: '  ', docs: '  ' },
    'techLevel': { detail: '  ', docs: '  ' },
    'buildSpeed': { detail: '  ', docs: '  ' },
    'radius': { detail: '  ', docs: '  ' },
    'isBio': { detail: '  ', docs: 'является ли юнит органическим (после смерти будет оставлять пятно)' },
    'isBug': { detail: '  ', docs: '  ' },
    'isBuilder': { detail: '  ', docs: '  ' },
    'maxHp': { detail: 'максимальное кол.во хп', docs: '  ' },
    'selfRegenRate': { detail: '  ', docs: '  ' },
    'maxShield': { detail: '  ', docs: '  ' },
    'startShieldAtZero': { detail: '  ', docs: '  ' },
    'energyStartingPercentage': { detail: '  ', docs: '  ' },
    'energyNeedsToRechargeToFull': { detail: '  ', docs: '  ' },
    'armour': { detail: 'покозатель брони', docs: 'покозатель брони уменьшает урон наносящийся юниту на столько сколько указано в этом пораметре (не в процентах)' },
    'armourMinDamageToKeep': { detail: '  ', docs: '  ' },
    'borrowResourcesWhileAlive': { detail: '  ', docs: '  ' },
    'generation_resources': { detail: '  ', docs: '  ' },
    'generation_active': { detail: '  ', docs: '  ' },
    'generation_credits': { detail: '  ', docs: '  ' },
    'generation_delay': { detail: '  ', docs: '  ' },
    'displayText': { detail: '  ', docs: '  ' },
    'displayDescription': { detail: '  ', docs: '  ' },
    'ShowInEditor': { detail: '  ', docs: '  ' },
    'MaxShield': { detail: '  ', docs: '  ' },
    'experemental': { detail: '  ', docs: '  ' },
    'ShieldRegen': { detail: '  ', docs: '  ' },
    'image': { detail: '  ', docs: '  ' },
    'image_turret': { detail: '  ', docs: '  ' },
    'dust_effect': { detail: '  ', docs: '  ' },
    'image_shadow': { detail: '  ', docs: '  ' },
    'canAttackNotTouchingWaterUnits': { detail: '  ', docs: '  ' },
    'turretMultiTargeting': { detail: '  ', docs: '  ' },
    'canAttackLandUnits': { detail: '  ', docs: '  ' },
    'canAttackUnderwaterUnits': { detail: '  ', docs: '  ' },
    'turretSize': { detail: '  ', docs: '  ' },
    'maxAttackRange': { detail: '  ', docs: '  ' },
    'projectile': { detail: '  ', docs: '  ' },
    'delay': { detail: '  ', docs: '  ' },
    'warmup': { detail: '  ', docs: '  ' },
    'recoilOffset': { detail: '  ', docs: '  ' },
    'recoilOutTime': { detail: '  ', docs: '  ' },
    'canShoot': { detail: '  ', docs: '  ' },
    'canAttackFlyingUnits': { detail: '  ', docs: '  ' },
    'laserDefenceEnergyUse': { detail: '  ', docs: '  ' },
    'targetGroundlife': { detail: '  ', docs: '  ' },
    'directDamage': { detail: '  ', docs: '  ' },
    'deflectionPower': { detail: '  ', docs: '  ' },
    'movementType': { detail: '  ', docs: '  ' },
    'moveSpeed': { detail: '  ', docs: '  ' },
    'maxTurnSpeed': { detail: '  ', docs: '  ' },
    'LAND': { detail: 'наземный', docs: 'наземный параметр  используется в определении типа юнита и в возможности атаковать данный тип ' },
    'AIR': { detail: 'воздушный', docs: 'летающий параметр  используется в определении типа юнита и в возможности атаковать данный тип ' },
    'HOVER': { detail: 'ховер(парящий)', docs: 'парящий ходит по зеле и воде параметр  используется в определении типа юнита и в возможности атаковать данный тип ' },
    'WATER': { detail: 'водный', docs: 'водный ходит по воде параметр  используется в определении типа юнита и в возможности атаковать данный тип ' },
    'OVER_CLIFF_WATER': { detail: '  ', docs: '  ' },
    'attach_x': { detail: '  ', docs: '  ' },
    'attach_y': { detail: '  ', docs: '  ' },
    'generation_delay': { detail: '  ', docs: '  ' },
    'generation_credits': { detail: '  ', docs: '  ' },
    'transportUnitsBlockAirAndWaterUnits': { detail: '  ', docs: '  ' },
    'transportUnitsRequireMovementType': { detail: '  ', docs: '  ' },
    'transportUnitsRequireTag': { detail: '  ', docs: 'По умолчанию истинно. Этот отряд может транспортировать только НАЗЕМНЫЕ отряды, если это правда. transportUnitsBlockAirAndWaterUnits: false ' },
    'maxTransportingUnits': { detail: '  ', docs: 'Количество слотов, которые имеет этот юнит для транспортировки других юнитов.' },
    'transportSlotsNeeded': { detail: '  ', docs: 'По умолчанию — 1. Количество слотов, которые этот юнит использует в транспорте, в экспериментальных случаях часто' },
    'isVisible': { detail: '  ', docs: ' ' },
    'requireConditional': { detail: '  ', docs: ' ' },
    'temporarilyAddTags': { detail: '  ', docs: ' ' },
    'isLocked': { detail: '  ', docs: ' ' },
    'isLockedMessage': { detail: '  ', docs: ' ' },
    'alsoQueueAction': { detail: '  ', docs: ' ' },
    'autoTrigger': { detail: '  ', docs: ' ' },
    'pos': { detail: '  ', docs: ' ' },
    'text': { detail: '  ', docs: ' ' },
    'addResources': { detail: '  ', docs: ' ' },
    'isLockedAltMessage': { detail: '  ', docs: ' ' },
    'description': { detail: '  ', docs: ' ' },
    'buildingSelectionOffset': { detail: '  ', docs: ' ' },
    'defineUnitMemory': { detail: '  ', docs: ' ' },       
    'slave': { detail: '  ', docs: ' ' },
    'shoot_sound': { detail: '  ', docs: ' ' },
    'shoot_flame': { detail: '  ', docs: ' ' },
    'shoot_light': { detail: '  ', docs: ' ' },
    'recoilReturnTime': { detail: '  ', docs: ' ' },       
    'idleSweepAngle': { detail: '  ', docs: ' ' },
    'idleSweepDelay': { detail: '  ', docs: ' ' },
    'idleSweepSpeed': { detail: '  ', docs: ' ' },
    'shootDelay': { detail: '  ', docs: ' ' },
    'attachedTo': { detail: '  ', docs: ' ' },
    'turretTurnSpeed': { detail: '  ', docs: ' ' },        
    'canAttack': { detail: '  ', docs: ' ' },
    'shadowOffsetX': { detail: '  ', docs: ' ' },
    'shadowOffsetY': { detail: '  ', docs: ' ' },
    'scaleFrom': { detail: '  ', docs: ' ' },
    'image_wreak': { detail: '  ', docs: ' ' },
    'total_frames': { detail: '  ', docs: ' ' },
    'alpha': { detail: '  ', docs: ' ' },
    'ySpeedRelativeRandom': { detail: '  ', docs: ' ' },
    'priority': { detail: '  ', docs: ' ' },
    'drawUnderUnits': { detail: '  ', docs: ' ' },
    'dirOffsetRandom': { detail: '  ', docs: ' ' },
    'hSpeed': { detail: '  ', docs: ' ' },
    'ySpeedRelative': { detail: '  ', docs: ' ' },
    'xSpeedRelativeRandom': { detail: '  ', docs: ' ' },
    'scaleTo': { detail: '  ', docs: ' ' },
    'life': { detail: '  ', docs: ' ' },
    'attachedToUnit': { detail: '  ', docs: ' ' },
    'isBuilding': { detail: '  ', docs: ' ' },
    'displayType': { detail: '  ', docs: ' ' },
    'displayDescription_ru': { detail: '  ', docs: ' ' },
    'constructionFootprint': { detail: '  ', docs: ' ' },
    'footprint': { detail: '  ', docs: ' ' },
    'fogOfWarSightRange': { detail: '  ', docs: ' ' },
    'displayDescription_zh': { detail: '  ', docs: ' ' },
    'autoTriggerCooldownTime': { detail: '  ', docs: ' ' },
    'autoTriggerCooldownTime_allowDangerousHighCPU': { detail: '  ', docs: ' ' },
    'addEnergy': { detail: '  ', docs: ' ' },
    'displayType': { detail: '  ', docs: ' ' },
    'displayText_ru': { detail: '  ', docs: ' ' },
    'displayText_zh': { detail: '  ', docs: ' ' },
    'shoot_sound': { detail: '  ', docs: ' ' },
    'shoot_flame': { detail: '  ', docs: ' ' },
    'shoot_light': { detail: '  ', docs: ' ' },
    'recoilReturnTime': { detail: '  ', docs: ' ' },
    'idleSweepAngle': { detail: '  ', docs: ' ' },
    'idleSweepDelay': { detail: '  ', docs: ' ' },
    'idleSweepSpeed': { detail: '  ', docs: ' ' },
    'buildingSelectionOffset': { detail: '  ', docs: ' ' },
    'experimental': { detail: '  ', docs: ' ' },
    'convertTo': { detail: '  ', docs: 'превращает текущего юнита в указанного' },
    'copyFrom': { detail: '  ', docs: ' ' },
    'text_zh': { detail: '  ', docs: ' ' },
    'text_ru': { detail: '  ', docs: ' ' },
    'text_es': { detail: '  ', docs: ' ' },
    'limitingRange': { detail: '  ', docs: ' ' },
    'resetAngle': { detail: '  ', docs: ' ' },
    'overrideAndReplace': { detail: '  ', docs: ' ' },
    'showInEditor': { detail: '  ', docs: ' ' },
    'areaDamage': { detail: '  ', docs: 'урон по радиусу' },
    'areaRadius': { detail: '  ', docs: 'радиус дамага' },
    'targetHeight': { detail: '  ', docs: ' ' },
    'builtFrom_1_name': { detail: '  ', docs: ' ' },
    'builtFrom_2_name': { detail: '  ', docs: ' ' },
    'turnAcceleration': { detail: '  ', docs: ' ' },
    'moveSlidingMode': { detail: '  ', docs: ' ' },
    'moveIgnoringBody': { detail: '  ', docs: ' ' },
    'reverseSpeedPercentage': { detail: '  ', docs: ' ' },
    'upgradedFrom': { detail: '  ', docs: ' ' },
    'whenBuilding_cannotMove': { detail: '  ', docs: ' ' },
    'whenBuilding_rotateTo': { detail: '  ', docs: ' ' },
    'whenBuilding_rotateTo_orBackwards': { detail: '  ', docs: ' ' },
    'speed': { detail: '  ', docs: 'скорость' },
    'drawSize': { detail: '  ', docs: ' ' },
    'description': { detail: '  ', docs: ' ' },
    'flame': { detail: '  ', docs: ' ' },   
    'hitSound': { detail: '  ', docs: ' ' },
    'instant': { detail: '  ', docs: ' ' }, 
    'speed': { detail: '  ', docs: ' ' },
    'drawSize': { detail: '  ', docs: ' ' },
    'turnSpeedAcceleration': { detail: '  ', docs: ' ' },
    'turnSpeed': { detail: '  ', docs: ' ' },
    'isFixedFiring': { detail: '  ', docs: ' ' },
    'turretRotateWithBoby': { detail: '  ', docs: ' ' },
    'tags': { detail: '  ', docs: ' ' },
    'builtFrom_1_pos': { detail: '  ', docs: ' ' },
    'dustEffect': { detail: '  ', docs: ' ' },
    'image_pl': { detail: '  ', docs: ' ' },
    'image_p2': { detail: '  ', docs: ' ' },
    'softCollisionOnALL': { detail: '  ', docs: ' ' },
    'softCollisionOnAll': { detail: '  ', docs: ' ' },
    'description': { detail: '  ', docs: ' ' },
    'teamColorsOnTurret': { detail: '  ', docs: ' ' },
    'lock_body_rotation_with_main_turret': { detail: '  ', docs: ' ' },
    'turretRotateWithBody': { detail: '  ', docs: ' ' },
    'shoot_sound_vol': { detail: '  ', docs: ' ' },
    'size': { detail: '  ', docs: ' ' },
    'largeHitEffect': { detail: '  ', docs: ' ' },
    'frame': { detail: '  ', docs: ' ' },
    'effectOnCreate': { detail: '  ', docs: ' ' },
    'lightSize': { detail: '  ', docs: ' ' },
    'animateFrameStart': { detail: '  ', docs: ' ' },
    'animateFrameEnd': { detail: '  ', docs: ' ' },
    'animateFramePingPong': { detail: '  ', docs: ' ' },
    'animateFrameSpeed': { detail: '  ', docs: ' ' },
    'fadeOut': { detail: '  ', docs: ' ' },
    'liveAfterAttachedDies': { detail: '  ', docs: ' ' },
    'physics': { detail: '  ', docs: ' ' },
    'action_deploy]': { detail: '  ', docs: ' ' },
    'lightColor': { detail: '  ', docs: ' ' },
    'core]': { detail: 'основная секция', docs: 'основная секция' },
    'graphics]': { detail: '  ', docs: ' ' },
    'action_deploy]': { detail: '  ', docs: ' ' },
    'attack]': { detail: '  ', docs: ' ' },
    'movement]': { detail: '  ', docs: ' ' },
    'ai]': { detail: '  ', docs: ' ' },
    'effect_flame]': { detail: '  ', docs: ' ' },
    'comment_action_reload]': { detail: '  ', docs: ' ' },
    'leg_': { detail: '  ', docs: ' ' },
    'effect_smoke]': { detail: '  ', docs: ' ' },
    'effect_muzzleFlame]': { detail: '  ', docs: ' ' },
    'animation_': { detail: '  ', docs: ' ' },
    'canBuild_': { detail: '  ', docs: ' ' },
    'exit_x': { detail: '  ', docs: ' ' },
    'exit_y': { detail: '  ', docs: ' ' },
    'dont_load' : { detail: '  ', docs: ' ' },
    'idleDir' : { detail: '  ', docs: ' ' },
    'invisible': { detail: '  ', docs: 'видел ли обект' },
    'CustomUnitMetadata': { detail: '  ', docs: ' ' },
    'displayRadius': { detail: '  ', docs: ' ' },
    'energyMax': { detail: '  ', docs: ' ' },
    'energyRegen': { detail: '  ', docs: ' ' },
    'movementEffect': { detail: '  ', docs: ' ' },
    'movementEffectRate': { detail: '  ', docs: ' ' },
    'explodeEffect': { detail: '  ', docs: ' ' },
    'targetGround': { detail: '  ', docs: ' ' },
    'targetGroundSpread': { detail: '  ', docs: ' ' },
    'targetSpeed': { detail: '  ', docs: ' ' },
    'trailEffect': { detail: '  ', docs: ' ' },
    'yOffsetRelative': { detail: '  ', docs: ' ' },
    'xOffsetRelative': { detail: '  ', docs: ' ' },
    'energyUsage': { detail: '  ', docs: ' ' },
    'dirSpeedRandom': { detail: '  ', docs: ' ' },
    'atmospheric': { detail: '  ', docs: ' ' },
    'buildPriority': { detail: '  ', docs: ' ' },
    'moveSlidingDir': { detail: '  ', docs: ' ' },
    'slowDeathFall': { detail: '  ', docs: ' ' },
    'fadeInTime': { detail: '  ', docs: ' ' },
    'hSpeedRandom': { detail: '  ', docs: ' ' },
    'if' : { detail: '  ', docs: ' ' },
    'self' : { detail: '  ', docs: ' ' },
    'areaHitUnderwaterAlways': { detail: '  ', docs: ' ' },
    'trailEffectRate': { detail: '  ', docs: ' ' },
    'moveWithParent': { detail: '  ', docs: ' ' },
    'idleDirReversing': { detail: '  ', docs: ' ' },
    'aimOffsetSpread': { detail: '  ', docs: ' ' },
    'autoTargetingOnDeadTarget': { detail: '  ', doc: '  '},
    'ROOT': { detail: '  ', doc: '  '},
    'animation_moving_start': { detail: '  ', docs: ' ' },
    'animation_moving_end': { detail: '  ', docs: ' ' },
    'animation_attack_start': { detail: '  ', docs: ' ' },
    'animation_attack_end': { detail: '  ', docs: ' ' },
    'animation_idle_start': { detail: '  ', docs: ' ' },
    'animation_idle_end': { detail: '  ', docs: ' ' },
    'animation_moving_speed': { detail: '  ', docs: ' ' },
    'animation_attack_speed': { detail: '  ', docs: ' ' },
    'animation_idle_speed': { detail: '  ', docs: ' ' },
    'whenBuilding_playAnimation': { detail: 'запускает указаную анимацию', docs: 'запускает указаную анимацию когда сектор `[action_deploy]` активен' },
    'CUSTOM': { detail: '  ', docs: ' ' },
    'self.isUnderwater()': { detail: '  ', docs: ' ' },
    'self.isAtGroundHeight()': { detail: '  ', docs: ' ' },
    'self.isFlying()': { detail: '  ', docs: ' ' },
    'self.isMoving()': { detail: '  ', docs: ' ' },
    'self.isAtTopSpeed()': { detail: '  ', docs: ' ' },
    'self.isInWater()': { detail: '  ', docs: ' ' },
    'self.isOverwater()': { detail: '  ', docs: ' ' },
    'self.isOverLiquid()': { detail: '  ', docs: ' ' },
    'self.isOverClift()': { detail: '  ', docs: ' ' },
    'self.isOverPassableTile()': { detail: '  ', docs: ' ' },
    'self.isOverOpenLand()': { detail: '  ', docs: ' ' },
    'self.hasResources()': { detail: '  ', docs: ' ' },
    'self.resource()': { detail: '  ', docs: ' ' },
    'self.isResourceLargerThan()': { detail: '  ', docs: ' ' },
    'self.hp()': { detail: '  ', docs: ' ' },
    'self.height()': { detail: '  ', docs: ' ' },
    'self.ammo()': { detail: '  ', docs: ' ' },
    'self.isAmmoEmpty()': { detail: '  ', docs: ' ' },
    'self.ammoIncludingQueued()': { detail: '  ', docs: ' ' },
    'self.energy()': { detail: '  ', docs: ' ' },
    'self.energyIncludingQueued() ': { detail: '  ', docs: ' ' },
    'self.isEnergyFull() ': { detail: '  ', docs: ' ' },
    'self.isEnergyEmpty() ': { detail: '  ', docs: ' ' },
    'self.shield() ': { detail: '  ', docs: ' ' },
    'self.kills() ': { detail: '  ', docs: ' ' },
    'self.queueSize() ': { detail: '  ', docs: ' ' },
    'game.nukesEnabled() ': { detail: '  ', docs: ' ' },
    'self.hasFlag() ': { detail: '  ', docs: ' ' },
    'self.tags() ': { detail: '  ', docs: ' ' },
    'self.globalTeamTags() ': { detail: '  ', docs: ' ' },
    'self.transportingCount() ': { detail: '  ', docs: ' ' },
    'self.vnumberOfAttachedUnits() ': { detail: '  ', docs: ' ' },
    'self.isAttacking() ': { detail: '  ', docs: ' ' },
    'self.hasActiveWaypoint() ': { detail: '  ', docs: ' ' },
    'self.transportingUnitWithTags() ': { detail: '  ', docs: ' ' },
    'self.hasParent() ': { detail: '  ', docs: ' ' },
    'self.hasTakenDamage()': { detail: '  ', docs: ' ' },
    'self.timeAlive() ': { detail: '  ', docs: ' ' },
    'self.lastConverted() ': { detail: '  ', docs: ' ' },
    'self.customTimer() ': { detail: '  ', docs: ' ' },
    'self.isOnNeutralTeam() ': { detail: '  ', docs: ' ' },
    'self.numberOfUnitsInTeam() ': { detail: '  ', docs: ' ' },
    'self.numberOfUnitsInAllyNotOwnTeam() ': { detail: '  ', docs: ' ' },
    'self.numberOfUnitsInEnemyTeam() ': { detail: '  ', docs: ' ' },
    'self.numberOfUnitsInNeutralTeam() ': { detail: '  ', docs: ' ' },
    'self.numberOfUnitsInAggressiveTeam()': { detail: '  ', docs: ' ' },
    'self.hasUnitInTeam() ': { detail: '  ', docs: ' ' },
    'self.noUnitInTeam() ': { detail: '  ', docs: ' ' },
    'self.isControlledByAI()': { detail: '  ', docs: ' ' },
    'canPlayerCancel': { detail: '  ', docs: ' ' },
    'hOffset': { detail: '  ', docs: ' ' },
    'dirOffset': { detail: '  ', docs: ' ' },
    'dirSpeed': { detail: '  ', docs: ' ' },
    'alwayStartDirAtZero': { detail: '  ', docs: ' ' },
    'spawnEffects': { detail: '  ', docs: ' ' },
    'canRepairBuildings': { detail: '  ', docs: ' ' },
    'canRepairUnits': { detail: '  ', docs: ' ' },
    'autoRepair': { detail: '  ', docs: ' ' },
    'nanoRange': { detail: '  ', docs: ' ' },
    'nanoBuildSpeed': { detail: '  ', docs: ' ' },
    'nanoRepairSpeed': { detail: '  ', docs: ' ' },
    'canReclaimResources': { detail: '  ', docs: ' ' },
    'isLockedMessage_ru': { detail: '  ', docs: ' ' },
    'availableInDemo': { detail: '  ', docs: ' ' },
    'displayName': { detail: '  ', docs: ' ' },
    'hidden': { detail: '  ', docs: ' ' },
    'xOffsetRelativeRandom': { detail: '  ', docs: ' ' },
    'yOffsetRelativeRandom': { detail: '  ', docs: ' ' },
    'hOffset': { detail: '  ', docs: ' ' },
    'physicsGravity': { detail: '  ', docs: ' ' },
    'holdDisMin_maxMovingLegs': { detail: '  ', docs: ' ' },
    'estimatingPositionMultiplier': { detail: '  ', docs: ' ' },
    'noneInBaseExtraPriority': { detail: '  ', docs: ' ' },
    'slowDeathFallSmoke': { detail: '  ', docs: ' ' },
    'useAsBuilder': { detail: '  ', docs: ' ' },
    'useAsAttacker': { detail: '  ', docs: ' ' }
}